# Generated by Django 4.2.1 on 2024-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cart_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product',
            name='img',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
