# Generated by Django 4.2.1 on 2024-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cart_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.URLField(default='/'),
        ),
    ]
