# Generated by Django 4.2.1 on 2024-06-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='description',
            field=models.TextField(default='jfjnj'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='ff'),
        ),
    ]
